### ISSUE TITLE
Get latest data for all states

### ISSUE THREAD

**Issue by nilskuhn** [fabianhinz/rkicasesapi#7]
Hi,

first thanks first for providing the API, great! Would be nice, if RKI would provide the data via REST itself, but well...

I would like to get latest 30 days for all federal states. Unfortunately, the endpoint for all states provides 30 days from the beginning of the recording in march 2020. Could you adapt the endoint for all states to
1) sort descending OR
2) add a parameter `fromDate` so that one could define starting point for the 30 days?

Regards, Nils

**Comment by fabianhinz** [comment]
Hi, 
I could have a look next week. Just FYI: at the beginning of the development I was parsing the data from the html document. A few weeks later I discovered multiple open apis which are hosted by arcgis.  You can retrieve a list of those apis with the following google search:
 *arcgis rki site:https://hub.arcgis.com/datasets*
The current implementation is nothing but a wrapper around some of those apis. You might find the data you are looking for here:
- https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Coronaf%C3%A4lle_in_den_Bundesl%C3%A4ndern/FeatureServer/0/query?where=1%3D1&outFields=LAN_ew_GEN,Fallzahl,faelle_100000_EW,Death&returnGeometry=false&outSR=4326&f=json
- https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19_Recovered_BL/FeatureServer/0/query?f=json&where=Bundesland%20IS%20NOT%20NULL&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=Bundesland,Genesen,DiffVortag,Datenstand&cacheHint=true

**Comment by nilskuhn** [comment]
Hi Fabian,

I actually did an evaluation of existing API's, but didn't find one providing RKI numbers of cases and deaths for the past. The ESRI API's you are referencing also just provide the current state of these numbers. Because I don't want to build up an own persistence for my use case, your approach, fetching the data continuously, persisting it and provide its history via API would perfectly fit for me. If you do know another API matching this needs please let me know.

As always, time is limited ;) but please let me know, if I may support with this.

**Comment by fabianhinz** [comment]
Hi Nils,

i've just pushed some changes
for starters you might wanna check out the postman collection which is referenced in the ReadMe.md and in the /postman folder. 
To summarise the changes: 

`https://europe-west1-rkicasesapi.cloudfunctions.net/get/rkicases?state=Baden-W%C3%BCrttemberg&startAtDate=2021-01-04T14:13:19.216Z` will return the data for the past 30 days, starting with `startAtDate` in descending order. 

`https://europe-west1-rkicasesapi.cloudfunctions.net/get/rkirecovered?state=Baden-W%C3%BCrttemberg&startAtDate=2021-01-04T14:13:19.216Z` with a small change to the path param you can also get historical data for the number of recovered people for a given state.

Hope that fits your needs. if not feel free to open the issue again

**Comment by nilskuhn** [comment]
Thanks for extending to support `rkirecovered`, too (also I don't need that data personally for the moment). Thanks also for adding a startDate. Initially, I wanted to get all states data for 30 days in one request, but I already adjusted to make 16 separate requests and assemble the data on my side. So for me everything is fine with the current state. 

I would make these 16 requests once per hour or every two hours. Hope that is ok for you.

**Comment by fabianhinz** [comment]
Yup, no worries ;)
